// src/services/automationUtils.js
import { db } from '../firebase'
import { collection, addDoc, serverTimestamp } from 'firebase/firestore'

/**
 * Notifica eventos críticos al Bot de Telegram vía Cloud Functions
 */

const notifyAdmin = async (title, message) => {
  try {
    // La URL exacta que te dio la terminal
    const API_URL = 'https://us-central1-vi-studio-core.cloudfunctions.net/api'; 
    // Tu contraseña maestra real
    const MASTER_PASSWORD = 'noaunINASF24MDSAsda12ds'; 

    await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'system_alert', 
        password: MASTER_PASSWORD,
        payload: { title, message }
      })
    });
  } catch (e) {
    console.error("Error enviando alerta:", e);
  }
}

export const createAutoTask = async (leadId, title, priority = 'medium', category = 'general') => {
  // Si la tarea es HIGH, mandamos alerta a Telegram automáticamente
  if (priority === 'high') {
    await notifyAdmin("🚨 TAREA CRÍTICA", title);
  }

  return await addDoc(collection(db, "tasks"), {
    leadId,
    title: `[${category.toUpperCase()}] ${title}`,
    priority,
    status: 'pending',
    category, 
    createdAt: serverTimestamp(),
    isAutoGenerated: true
  })
}

export const logSystemEvent = async (type, description) => {
  // Notificar ingresos de dinero a Telegram
  if (type === 'REVENUE_IN') {
    await notifyAdmin("💰 NUEVOS FONDOS", description);
  }

  await addDoc(collection(db, "system_logs"), {
    type,
    description,
    timestamp: serverTimestamp()
  })
}